index:
    path: /
    controller: App\Controller\WeathercheckerController::index
check_weather_city:
    path: /check-weather/{city}
    controller: App\Controller\WeathercheckerController::checkWeather
